### ISSUE TITLE
Update links to old examples repo to point to the new examples repo

### ISSUE THREAD

**Issue by kito99** [jakartaee/jakartaee-tutorial#53]
The old Jakarta EE docs examples repo was deleted, and all of the content was moved here: https://github.com/eclipse-ee4j/jakartaee-examples/tree/main/tutorial. The tutorial needs to be updated to reflect this; all links to the old tutorials should point here.

**Comment by kito99** [comment]
@jhammen will be working on this.

**Comment by kito99** [comment]
@jhammen have you had a chance to look at this yet?

**Comment by jhammen** [comment]
only briefly but I freed up some time starting tomorrow to take a closer look

**Comment by kito99** [comment]
@jhammen we should also decide what to do change about direct links to the examples repo in the Jakarta Security chapter:  https://jakartaee.github.io/jakartaee-documentation/jakartaee-tutorial/current/security/security.html#_test_the_application

**Comment by kito99** [comment]
Also, I just remembered this needs to be done for the 9.1 branch and the 10 branch as well.

**Comment by jhammen** [comment]
> @jhammen we should also decide what to do change about direct links to the examples repo in the Jakarta Security chapter: https://jakartaee.github.io/jakartaee-documentation/jakartaee-tutorial/current/security/security.html#_test_the_application

Looks like the link there is already correct? https://github.com/eclipse-ee4j/jakartaee-examples

what do you see wrong there?

**Comment by kito99** [comment]
@jhammen never mind; I was thinking there was an indirect reference to the URL for the repo (like we have for the path name).
