### ISSUE TITLE
Update README.md and CONTRIBUTE.md links to reflect the new repo URLs (do this in all 3 repos)

### ISSUE THREAD

**Issue by kito99** [jakartaee/jakartaee-tutorial#60]
The repo URLs have changed from the virtua-tech to jakartaee organization: 

https://github.com/virtua-tech/jakartaee-tutorial -> https://github.com/jakartaee/jakartaee-tutorial
https://github.com/virtua-tech/jakartaee-tutorial-playbook -> https://github.com/jakartaee/jakartaee-documentation
https://github.com/virtua-tech/jakartaee-tutorial-ui -> https://github.com/jakartaee/jakartaee-documentation-ui

These need to be updated in the READMEs (they currently redirect).

Also, the README for `jakartaee-tutorial` can have the section with links to the wiki and issues removed, since those are now in Github.  Any other incorrect links should be fixed as well.

**Comment by kito99** [comment]
@jhammen feel free to do this one if you have the time. shouldn't take long.

**Comment by jhammen** [comment]
will take a look

**Comment by kito99** [comment]
thanks @jhammen !

**Comment by kito99** [comment]
@jhammen  can you add links to the relevant PRs?

**Comment by jhammen** [comment]
PRs:

https://github.com/jakartaee/jakartaee-tutorial/pull/75
https://github.com/jakartaee/jakartaee-documentation-ui/pull/22
https://github.com/jakartaee/jakartaee-documentation/pull/15

In my view I'm also seeing them above, they are the links with the "open" button on the right

**Comment by kito99** [comment]
doh! I may have missed that. My bad!
