### ISSUE TITLE
Migrate  "Chapter 1. Overview" and "Chapter 2. Using the Tutorial Examples" 

### ISSUE THREAD

**Issue by kito99** [jakartaee/jakartaee-tutorial#62]
Add these two chapters back to the navigation and migrate the Asciidoc files accordingly.

**Comment by kito99** [comment]
@jhammen this is a good candidate for you as well.

**Comment by jhammen** [comment]
content was already migrated, this is just a matter of linking it back into the navigation

**Comment by kito99** [comment]
@jhammen we need chapter 1 too; I updated the title accordingly,.

**Comment by jhammen** [comment]
> @jhammen we need chapter 1 too; I updated the title accordingly,.

OK I put that one in too, see PR above
