### ISSUE TITLE
Change "Full Profile" to "Jakarta EE Platform" across the board

### ISSUE THREAD

**Issue by kito99** [jakartaee/jakartaee-tutorial#67]
Any `.adoc` files that say "Full Profile" need to be updated to say "Jakarta EE Platform" instead.

**Comment by kito99** [comment]
@steven-ww done!

**Comment by steven-ww** [comment]
I'm about to raise the MR, just wondering if "Full Platform" should also be changed?

Example: _At least those compatible with "Web Profile" and "Full Platform" have a servlet container._

**Comment by kito99** [comment]
@steven-ww yes, please change "Full Platform" as well. 

You're correct about that line, too. Good catch! Perhaps reword it something like this:

> A Jakarta EE implementation that supports the Jakarta EE Platform also includes a Messaging provider.

**Comment by steven-ww** [comment]
@kito99 I've created the PR for your review.
