### ISSUE TITLE
Remove invalid links to Configuring Model Data section

### ISSUE THREAD

**Issue by kito99** [jakartaee/jakartaee-tutorial#69]
There are two links that point to a section that has since been removed. The section has title "Configuring Model Data" and was removed in this commit:

https://github.com/jakartaee/jakartaee-tutorial/commit/85372e78a79cf9cca84d28a4bcca3225158fb4b0

The links that still point there are in two files:

* dukes-bookstore002 in case studies

* faces-custom006: [Configuring Model Data] describes how the application stores these values.

**Comment by Jangyaseni666** [comment]
In these files, it has been asked to refer Configuring Model Data. So, when I remove it what shall I add as a replacement? or should I leave it as is?

**Comment by kito99** [comment]
You can just remove the entire sentence that makes the reference.

___

Kito D. Mann <https://kitomann.com/> | @kito99 <https://twitter.com/kito99> |
Java Champion | Google Developer Expert Alumni | LinkedIn
<https://www.linkedin.com/in/kitomann/>
Expert consulting and training: Cloud architecture and modernization,
Java/Jakarta EE, Web Components, Angular, Mobile Web
Virtua, Inc. | virtua.tech
+1 203-998-0403 <(203)%20998-0403>
<http://voice.google.com/calls?a=nc,%2B12039980403>
<http://voice.google.com/calls?a=nc,%2B12039980403>
<http://voice.google.com/calls?a=nc,%2B12039980403>
<http://voice.google.com/calls?a=nc,%2B12039980403>
<http://voice.google.com/calls?a=nc,%2B12039980403>
<http://voice.google.com/calls?a=nc,%2B12039980403>
<http://voice.google.com/calls?a=nc,%2B12039980403>
<http://voice.google.com/calls?a=nc,%2B12039980403>
<http://voice.google.com/calls?a=nc,%2B12039980403>
<http://voice.google.com/calls?a=nc,%2B12039980403>
<http://voice.google.com/calls?a=nc,%2B12039980403>

* Enterprise development, front and back. Listen to Stackd Podcast
<http://stackdpodcast.com/>.
* Speak at conferences? Check out SpeakerTrax <https://speakertrax.com/>.

From: Jangyaseni Sahoo ***@***.***> ***@***.***>
Reply: jakartaee/jakartaee-tutorial
***@***.***>
***@***.***>
Date: November 18, 2023 at 10:56:13 PM
To: jakartaee/jakartaee-tutorial ***@***.***>
***@***.***>
CC: Kito D. Mann ***@***.***>
***@***.***>, Author ***@***.***>
***@***.***>
Subject:  Re: [jakartaee/jakartaee-tutorial] Remove invalid links to
Configuring Model Data section (Issue #69)

In these files, it has been asked to refer Configuring Model Data. So, when

**Comment by Jangyaseni666** [comment]
okay. Thankyou!

**Comment by Jangyaseni666** [comment]
I have made a PR. Please approve :)

**Comment by kito99** [comment]
Thanks, @Jangyaseni666. Please make sure you reference the PR like so: #83

**Comment by sharsha315** [comment]
Hi @kito99, is this issue still open. Can I have the opportunity to work on this issue.

**Comment by kito99** [comment]
@sharsha315 sorry, I should have closed this. Do you see any other issues in which you're interested?
