### ISSUE TITLE
Update the old repo's README file to point users to the new repo

### ISSUE THREAD

**Issue by kito99** [jakartaee/jakartaee-tutorial#78]
Update the README file in [the old repo](https://github.com/eclipse-ee4j/jakartaee-tutorial) to state that the project has been moved and that this repo is no longer maintained.

**Comment by Jangyaseni666** [comment]
I would like to work on this. Please assign it to me!

**Comment by Jangyaseni666** [comment]
I have sent a PR on the old repo with the necessary changes. Please do approve it, if it helps.
