### ISSUE TITLE
Migrate "Chapter 1. Overview" and "Chapter 2. Using the Tutorial Examples" in the release/9.1 branch

### ISSUE THREAD

**Issue by kito99** [jakartaee/jakartaee-tutorial#79]
This is the same task as #62  but for the `release/9.1` branch.

**Comment by kito99** [comment]
@jhammen good candidate.

**Comment by jhammen** [comment]
I don't think there's anything to do here? All the content has been migrated to antora and the release/9.1 branch never underwent the chapter re-org that lost these chapters, they are still there in the left nav

https://jakartaee.github.io/jakartaee-documentation/jakartaee-tutorial/9.1/index.html

**Comment by kito99** [comment]
You're right. My bad.
