### ISSUE TITLE
updating the required  knowledge of java to the new tutorial site

### ISSUE THREAD

**Issue by Just-some-one** [jakartaee/jakartaee-tutorial#80]
step to the issue

1) go to [before_you_read_this_book](https://jakartaee.github.io/jakartaee-documentation/jakartaee-tutorial/current/#_before_you_read_this_book)
2) it point to the jdk 8 tutorial "https://docs.oracle.com/javase/tutorial/index.html"

it should be updated to point to new home for java "https://dev.java/learn/"

thanks for your great work and have a nice day :)

**Comment by Jangyaseni666** [comment]
I am working on it. Can you assign it to me?

**Comment by Jangyaseni666** [comment]
the issue is resolved and the PR is merged in PR #83

**Comment by Jangyaseni666** [comment]
@kito99  the issue can be closed now

**Comment by Just-some-one** [comment]
> the issue is resolved and the PR is merged in PR #83

**Comment by Just-some-one** [comment]
> @kito99 the issue can be closed now

done and thanks for your help and have a nice day :)
