### ISSUE TITLE
Rename all of the Jakarta REST artifacts from "jaxrs" to "rest"

### ISSUE THREAD

**Issue by kito99** [jakartaee/jakartaee-tutorial#90]
Any file or folder with "jaxrs" in the name should have "jaxrs" replaced with "rest".  Please make sure all references in `.adoc` files are updated as well, and test your changes.

This should be applied to both the `main` and `release/9.1` branches.

**Comment by Harsh4902** [comment]
@kito99 I want to work on this issue. Can you guide me from where I should start?

**Comment by kito99** [comment]
Hello @Harsh4902 , glad to hear it! 

Basically, all you have to do is fork this repo, follow the instructions above, and then create a PR. You'll need to do it separately for both the `release/9.1` and `main` branches.

If you want to see what it looks like, youi'll also need to fork the [jakartaee/jakartaee-documentation](https://github.com/jakartaee/jakartaee-documentation) repo and follow the instructions there (you'll want to use Author mode). This is optional, though.

**Comment by kito99** [comment]
I've assigned this to myself as only committers can be assigned. But I'll work with you to complete the task.

**Comment by Harsh4902** [comment]
@kito99 Thank you for your support.

**Comment by Harsh4902** [comment]
@kito99 Please review this PR and suggest the changes if required. If there are no any changes then I will rise separate PR for `main` branch.
