### ISSUE TITLE
Update Further Reading links

### ISSUE THREAD

**Issue by kito99** [jakartaee/jakartaee-tutorial#99]
Many chapters include "Further Information" sections that have a link to the specification and additional resources. Please review these sections and update the links to point to the Jakarta EE 10 version of the specification, and verify that the other links work and are still relevant.

This needs to be done for all chapters _except_ for ones handled by other tickets:

* Jakarta REST
* Jakarta Persistence
* Jakarta Servlet
* Jakarta CDI

The easiest way find the files you need to update is to search for "== Further Information" in your IDE or text editor:

![2023-12-14_09-49-56](https://github.com/jakartaee/jakartaee-tutorial/assets/3187538/cfcfd0cc-a95d-428a-9fc4-6f46c25319db)

You can find the specifications here: https://jakarta.ee/specifications/. You'll want the latest version that is _not_ in development, since Jakarta EE 10 was released last year.

**Comment by Harsh4902** [comment]
@kito99 I want to work on this issue.

**Comment by kito99** [comment]
@Harsh4902 you got it! thanks!

**Comment by Harsh4902** [comment]
@kito99 do I just need to replace for example `== Further Information about Jakarta Bean Validation` with the `https://jakarta.ee/specifications/bean-validation/3.1/` or I have to put some more information? If so then what information should I put?

**Comment by kito99** [comment]
@Harsh4902 You don't need to add any new information. Just go through each of the chapters mentioned above and make sure the links in the Further Information section are updated for Jakarta EE 10. The example you gave for Bean Validation is correct.

**Comment by AbdAlRahmanGad** [comment]
@kito99 Hi, is this issue still open for commits? can I take it?

**Comment by kito99** [comment]
@AbdAlRahmanGad let's give @Harsh4902 one last chance. @Harsh4902 do you have time to work on this soon?

**Comment by Harsh4902** [comment]
@kito99 I have already raised a PR for this. Please review it so I can get an idea of which things need to be changed.

**Comment by kito99** [comment]
PR #103
